# pyproject.toml
[project]
name = "comfyui-complex-prompt"
description = "ComfyUI node for working with complex prompts with support for variables, randomness, and basic logic."
version = "0.0.1"
license = { text = "MIT" }
dependencies  = [
    "dynamicprompts>=0.31.0",
    "simpleeval>=1.0.7",
]

[project.urls]
Repository = "https://github.com/ArtemKo7v/ComfyUI-Complex-Prompt"

[tool.comfy]
PublisherId = "artemko7v"
DisplayName = "ComfyUI Complex Prompt Nodes"
